Bug/167/windows10
vcync/modV pull request #285
Opened 2018-10-21 14:07 UTC by TimPietrusky

* Updated node-sass to 4.9.4
* Added a note into the README saying that the `windows-build-tools` are required on Windows 10

2018-10-26 15:19 UTC, 2xAA requested changes

2018-10-26 15:19 UTC, 2xAA commented on README.md
> +In order to use modV on Windows 10 you have to install the `windows-build-tools`:
Can we change "use" to "build"?

2018-10-27 20:47 UTC, TimPietrusky commented on README.md
> +In order to use modV on Windows 10 you have to install the `windows-build-tools`:
I updated the README to use "build" instead of "use".

2018-10-28 15:04 UTC, 2xAA approved these changes

2018-10-28 15:04 UTC, merged