fix(slow-start-up): refactors worker/modv lifecycle and module loading
vcync/modV pull request #618
Opened 2021-07-02 17:11 UTC by 2xAA

The worker now reports to the renderer process when it's done loading. main.js is waiting for modV's ready promise to resolve before mounting the Vue application. modV also sends an event to the background process to show the main window and close the splash screen.

Speed gains can be measured on macOS (Intel). Windows seems about the same, but at least the UI isn't unresponsive while it's loading.

fixes #617

2021-07-16 10:45 UTC, TimPietrusky commented
@2xAA this looks super cool, thank you very much!

I just have one error:

1. Open modV
2. Reload modV
3. See the following error in a popup:

```js
Uncaught Exception:
TypeError: Object has been destroyed
at IpcMainImpl.eval (webpack:///./src/background.js?:123:16)
at IpcMainImpl.emit (events.js:327:22)
at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
at Object.emit (events.js:315:20)
```

This happens every time modV is reloaded.

2021-08-26 11:40 UTC, 2xAA commented
I actually want to hold off on this until #623 is merged as the queuing of messages improves start-up time drastically.
We can still merge this to have a nice splash-screen, once that error is fixed.

2021-08-31 20:57 UTC, TimPietrusky commented
@2xAA thanks for the fix. Now when I reload modV, the whole window is white (excluding the navigation) until everything is loaded. Maybe add a loading spinner to the main window background? So that it's indicating that the application is loading? 

And also could you please resolve the conflicts? 🙏

2021-08-31 20:57 UTC, TimPietrusky requested changes

2021-08-31 20:57 UTC, TimPietrusky commented on src/subpages/splash-screen/main.js
> +debugger;
Can you please get rid of the `debugger`?

2021-08-31 20:58 UTC, TimPietrusky commented on src/subpages/splash-screen/main.js
> +debugger;
This was resolved!

2021-09-14 21:02 UTC, TimPietrusky commented
@2xAA 

* Set background to default background color
* Added loading spinner to improve the waiting experience

What do you think?

2021-09-22 09:59 UTC, 2xAA commented
![Screenshot 2021-09-22 at 10 58 02](https://user-images.githubusercontent.com/554219/134323517-79a0035a-a225-4e82-a8f9-9b580249dd52.png)

@TimPietrusky looks good, though the splash screen now has a background and loading animation 😅

2021-10-23 11:54 UTC, TimPietrusky commented
@2xAA the issues have been addressed, please take another look!

2021-10-23 14:36 UTC, 2xAA commented
@TimPietrusky Awesome, seems to work fine :)

2021-10-23 14:37 UTC, merged

2021-11-09 22:04 UTC, 2xAA commented
:tada: This PR is included in version 3.19.0 :tada:

The release is available on [GitHub release](https://github.com/vcync/modV/releases/tag/3.19.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: