test: add playwright for e2e tests
vcync/modV pull request #828
Opened 2023-03-04 14:41 UTC by 2xAA

fix :#688

Started this again - fixed the window launch order which was preventing reliable testing previously.
Seems pretty solid this time around.

Not tested on any other OS than macOS.
To run tests:

```bash
yarn
yarn electron:build
npx playwright test
```

2023-03-04 14:49 UTC, 2xAA commented on package.json
> +    "asar": "^3.2.0",
May not be needed

2023-03-04 14:49 UTC, 2xAA commented on package.json
> +    "xvfb-maybe": "^0.2.1"
May not be needed

2023-03-04 14:50 UTC, 2xAA commented on tests/e2e/main.spec.js
> +// } from "electron-playwright-helpers";
Can remove, was following a tutorial

2023-03-04 14:50 UTC, 2xAA commented on tests/e2e/main.spec.js
> +// test("trigger IPC listener via main process", async () => {
Can remove, was following a tutorial

2023-03-04 14:51 UTC, 2xAA commented on tests/e2e/pageObjectModel/index.js
> +      // Playwright, why are you so bad at timings?
Unhappy about this hack, but it seems needed.

Luckily it seems like it's only teardown timing, so doesn't affect the running of the tests until the last.

2023-05-22 19:50 UTC, 2xAA commented on tests/e2e/pageObjectModel/index.js
> +    resolver = undefined;
Probably not needed

2023-05-22 19:54 UTC, 2xAA commented
<img width="1060" alt="Screenshot 2023-05-22 at 20 53 20" src="https://github.com/vcync/modV/assets/554219/78a514a4-0c08-4175-8956-0cef9c6edd8b">

2023-05-24 20:13 UTC, TimPietrusky requested changes
Everything is awesome, just one problem with the `groups/groupNameCanBeChanged.spec.js`. As we found out during the call, its related to my MacOS version.

2023-05-25 07:12 UTC, 2xAA commented
@TimPietrusky groupNameCanBeChanged is now fixed!

2023-05-25 07:13 UTC, 2xAA commented
<img width="892" alt="Screenshot 2023-05-25 at 08 12 57" src="https://github.com/vcync/modV/assets/554219/20363ebf-596a-454d-b301-5cb6978241b2">

2023-06-11 06:54 UTC, merged